[pytest]
;addopts = -v -s --html=reports/report.html
;addopts = --tracing on --output=test-results
addopts =  --html=report.html --headed
testpaths = tests
python_files = test_*.py
markers =
    smoke: smoke test cases
    regression: regression suite
    api: api testing
    selenium: for selenium based tests
    sanity: for sanity based tests

log_cli = true
log_cli_level = INFO
pythonpath = .